execute:
  - SilverStripe\Headless\GraphQL\ModelLoader
  - SilverStripe\Headless\GraphQL\OperationLoader
modelConfig:
  DataObject:
    type_formatter: 'SilverStripe\Core\ClassInfo::shortName'
    base_fields:
      ID: ID!
      HashID: String!
      TypeAncestry: '[[String]]'
      exists: Boolean!
    plugins:
      versioning: false
      inheritance:
        useUnionQueries: false
    operations:
      read:
        plugins:
          filter: true
      readOne:
        plugins:
          getByLink:
            after: filter
